# Generated by Django 5.2.7 on 2025-12-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Фото профиля (JPEG, PNG, GIF). Максимальный размер: 5MB', null=True, upload_to='users/profiles/'),
        ),
    ]
