# Generated by Django 5.2.7 on 2026-01-30 13:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0029_alter_card_category'),
        ('users', '0016_loginotp_ref_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='referral',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='cards.card'),
        ),
        migrations.AddField(
            model_name='referral',
            name='reward_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='reward_per_sqm',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10),
        ),
    ]
