# Generated by Django 5.2.7 on 2026-01-30 14:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_referral_options_referral_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
