# Generated by Django 5.2.7 on 2025-10-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='city',
            field=models.CharField(choices=[('Махачкала', 'Махачкала'), ('Каспийск', 'Каспийск')], default='Махачкала', max_length=255),
        ),
        migrations.AddField(
            model_name='card',
            name='house_type',
            field=models.CharField(choices=[('private', 'Частный дом'), ('apartment', 'Квартира')], default='apartment', max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='image',
            field=models.ImageField(upload_to='cards/img/'),
        ),
    ]
