# Generated by Django 5.1.7 on 2025-10-19 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_city_card_house_type_card_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='card',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
