# Generated by Django 5.1.7 on 2025-10-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_rating_card_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
