# Generated by Django 5.1.7 on 2025-11-03 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='card',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='building_material',
            field=models.CharField(choices=[('brick', 'Кирпичный'), ('panel', 'Панельный'), ('monolith', 'Монолитный')], default='brick', max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.CharField(choices=[('flat', 'Квартира'), ('new_building', 'Новостройка')], default='flat', max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='ceiling_height',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='card',
            name='elevator',
            field=models.CharField(choices=[('none', 'Нет'), ('passenger', 'Пассажирский'), ('cargo', 'Грузовой')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='floors_total',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='card',
            name='housing_account',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='parking',
            field=models.CharField(choices=[('none', 'Нет'), ('underground', 'Подземная')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='city',
            field=models.IntegerField(choices=[('1', 'Махачкала'), ('2', 'Каспийск'), ('3', 'Дербент')]),
        ),
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('preferred_time', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to='cards.card')),
            ],
        ),
    ]
