# Generated by Django 5.1.7 on 2025-11-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_area_card_balcony_card_building_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='city',
            field=models.IntegerField(choices=[('1', 'Махачкала'), ('2', 'Каспийск'), ('3', 'Дербент')], default=1),
        ),
    ]
