# Generated by Django 5.1.7 on 2025-11-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='city',
            field=models.IntegerField(choices=[(1, 'Махачкала'), (2, 'Каспийск'), (3, 'Дербент')], default=1),
        ),
    ]
