# Generated by Django 5.1.7 on 2025-11-03 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_card_city'),
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='developers.developer'),
        ),
    ]
