# Generated by Django 5.1.7 on 2025-11-09 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_card_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='cards/videos/')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='cards.card')),
            ],
        ),
    ]
