# Generated by Django 5.1.7 on 2025-11-10 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_cardvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='housing_account',
        ),
        migrations.CreateModel(
            name='CardDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cards/documents/')),
                ('title', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cards.card')),
            ],
        ),
    ]
