# Generated by Django 5.2.8 on 2025-12-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardquestion',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
