# Generated by Django 5.2.8 on 2025-12-11 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_cardquestion_answered_at'),
        ('developers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='cardquestion',
            name='answered_at',
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['title'], name='cards_card_title_f173ba_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['city'], name='cards_card_city_3a8e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['house_type'], name='cards_card_house_t_1104f2_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['price'], name='cards_card_price_a83c51_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['created_at'], name='cards_card_created_591b38_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['city', 'house_type'], name='cards_card_city_8b92b1_idx'),
        ),
    ]
