# Generated by Django 5.2.8 on 2025-12-11 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_alter_card_options_remove_cardquestion_answered_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dream House Assistant', max_length=100)),
                ('api_provider', models.CharField(choices=[('openai', 'OpenAI (GPT-4)'), ('anthropic', 'Anthropic (Claude)'), ('disabled', 'Отключен')], default='openai', max_length=50)),
                ('api_key', models.CharField(blank=True, help_text='Ключ API для провайдера (не видим в админке)', max_length=500, null=True)),
                ('model_name', models.CharField(default='gpt-4', help_text='Название модели (gpt-4, claude-3-opus и т.д.)', max_length=100)),
                ('system_prompt', models.TextField(default='Ты профессиональный консультант по недвижимости. Помогай пользователям найти идеальный дом.\nТы имеешь доступ к базе данных карточек недвижимости и можешь давать персонализированные рекомендации.\nОтвечай на русском языке, будь вежлив и информативен.', help_text='Системный промпт для AI')),
                ('temperature', models.FloatField(default=0.7, help_text='Температура модели (0-1). 0 = детерминированно, 1 = творческо')),
                ('max_tokens', models.IntegerField(default=500, help_text='Максимальное количество токенов в ответе')),
                ('is_active', models.BooleanField(default=True, help_text='Включен ли ассистент')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Ассистент',
                'verbose_name_plural': 'AI Ассистенты',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Сообщение пользователя')),
                ('response', models.TextField(blank=True, help_text='Ответ от AI', null=True)),
                ('tokens_used', models.IntegerField(default=0, help_text='Количество токенов использовано')),
                ('is_helpful', models.BooleanField(blank=True, help_text='Был ли ответ полезным (для улучшения AI)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referenced_cards', models.ManyToManyField(blank=True, help_text='Карточки, упомянутые в чате', related_name='mentioned_in_chats', to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='cards_chatm_user_id_42f0ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiscountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Текущая цена карточки', max_digits=12)),
                ('requested_price', models.DecimalField(decimal_places=2, help_text='Желаемая цена от пользователя', max_digits=12)),
                ('discount_percent', models.FloatField(blank=True, editable=False, help_text='Процент скидки (вычисляется автоматически)', null=True)),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Причина или комментарий к запросу', null=True)),
                ('admin_comment', models.TextField(blank=True, help_text='Комментарий администратора при отклонении/одобрении', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_requests', to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['card', 'status'], name='cards_disco_card_id_b4735d_idx'), models.Index(fields=['user', 'status'], name='cards_disco_user_id_a008d3_idx'), models.Index(fields=['-created_at'], name='cards_disco_created_895b17_idx')],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='Оценка релевантности (0-1)')),
                ('reason', models.CharField(blank=True, help_text='Причина рекомендации (город, тип, цена и т.д.)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['user', '-score'], name='cards_recom_user_id_3c0d53_idx'), models.Index(fields=['-created_at'], name='cards_recom_created_521472_idx')],
                'unique_together': {('user', 'card')},
            },
        ),
    ]
