# Generated by Django 5.2.8 on 2025-12-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_aiassistant_chatmessage_discountrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiassistant',
            name='api_provider',
            field=models.CharField(choices=[('openai', 'OpenAI (GPT-4)'), ('anthropic', 'Anthropic (Claude)'), ('deepseek', 'DeepSeek (R1)'), ('disabled', 'Отключен')], default='openai', max_length=50),
        ),
    ]
