# Generated by Django 5.2.8 on 2025-12-14 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0017_card_list_curations_carddocumentlist_viewhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='viewhistory',
            new_name='cards_viewh_user_id_1c293f_idx',
            old_name='vh_user_viewed_idx',
        ),
        migrations.RenameIndex(
            model_name='viewhistory',
            new_name='cards_viewh_card_id_c9a03a_idx',
            old_name='vh_card_viewed_idx',
        ),
        migrations.AlterField(
            model_name='carddocumentlist',
            name='name',
            field=models.CharField(help_text="Название подборки (например: 'Документы на квартиру', 'Правоустанавливающие документы')", max_length=255),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Сколько секунд пользователь просматривал карточку'),
        ),
        migrations.AlterUniqueTogether(
            name='viewhistory',
            unique_together={('user', 'card', 'viewed_at')},
        ),
    ]
