# Generated by Django 5.2.8 on 2025-12-16 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0023_alter_card_list_curations_review'),
        ('developers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на звонок', 'verbose_name_plural': 'Заявки на звонок'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-created_at'], 'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='carddocument',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'Документ квартиры', 'verbose_name_plural': 'Документы квартир'},
        ),
        migrations.AlterModelOptions(
            name='cardimage',
            options={'verbose_name': 'Фото квартиры', 'verbose_name_plural': 'Фото квартир'},
        ),
        migrations.AlterModelOptions(
            name='cardquestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='cardreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв о карточке', 'verbose_name_plural': 'Отзывы о карточках'},
        ),
        migrations.AlterModelOptions(
            name='cardvideo',
            options={'verbose_name': 'Видео квартиры', 'verbose_name_plural': 'Видео квартир'},
        ),
        migrations.AlterModelOptions(
            name='discountrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрос на скидку', 'verbose_name_plural': 'Запросы на скидки'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'История поиска', 'verbose_name_plural': 'История поиска'},
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to='cards.card', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обработана'),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='Предпочитаемое время'),
        ),
        migrations.AlterField(
            model_name='card',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='card',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Площадь м²'),
        ),
        migrations.AlterField(
            model_name='card',
            name='balcony',
            field=models.BooleanField(default=False, verbose_name='Балкон'),
        ),
        migrations.AlterField(
            model_name='card',
            name='building_material',
            field=models.CharField(choices=[('brick', 'Кирпичный'), ('panel', 'Панельный'), ('monolith', 'Монолитный')], default='brick', max_length=50, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.CharField(choices=[('flat', 'Квартира'), ('new_building', 'Новостройка')], default='flat', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='card',
            name='ceiling_height',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=3, verbose_name='Высота потолков'),
        ),
        migrations.AlterField(
            model_name='card',
            name='city',
            field=models.IntegerField(choices=[(1, 'Махачкала'), (2, 'Каспийск'), (3, 'Дербент')], default=1, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='card',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='developers.developer', verbose_name='Девелопер'),
        ),
        migrations.AlterField(
            model_name='card',
            name='elevator',
            field=models.CharField(choices=[('none', 'Нет'), ('passenger', 'Пассажирский'), ('cargo', 'Грузовой')], default='none', max_length=20, verbose_name='Лифт'),
        ),
        migrations.AlterField(
            model_name='card',
            name='floors_total',
            field=models.PositiveIntegerField(default=1, verbose_name='Этажей в доме'),
        ),
        migrations.AlterField(
            model_name='card',
            name='house_type',
            field=models.CharField(choices=[('private', 'Частный дом'), ('apartment', 'Квартира')], default='apartment', max_length=50, verbose_name='Тип дома'),
        ),
        migrations.AlterField(
            model_name='card',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='card',
            name='list_curations',
            field=models.TextField(blank=True, default='[]', help_text='JSON массив с объектами карточек для подборок. Каждый объект содержит: id, address, price, rooms, city, rating', verbose_name='Подборки'),
        ),
        migrations.AlterField(
            model_name='card',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='card',
            name='parking',
            field=models.CharField(choices=[('none', 'Нет'), ('underground', 'Подземная')], default='none', max_length=20, verbose_name='Парковка'),
        ),
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='card',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='card',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество оценок'),
        ),
        migrations.AlterField(
            model_name='card',
            name='rooms',
            field=models.PositiveIntegerField(default=1, verbose_name='Комнаты'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='carddocument',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cards.card', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='carddocument',
            name='document_list',
            field=models.ForeignKey(blank=True, help_text='Подборка, к которой относится документ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cards.carddocumentlist', verbose_name='Подборка'),
        ),
        migrations.AlterField(
            model_name='carddocument',
            name='file',
            field=models.FileField(upload_to='cards/documents/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='carddocument',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='carddocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Загружен'),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cards.card', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='image',
            field=models.ImageField(upload_to='cards/img/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='cardquestion',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='cardquestion',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cards.card', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='cardquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='cardquestion',
            name='question',
            field=models.TextField(verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='cardquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='cardreview',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cards.card', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='cardreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='cardreview',
            name='rating',
            field=models.PositiveIntegerField(default=5, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='cardreview',
            name='text',
            field=models.TextField(verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='cardreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='cardvideo',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='cards.card', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='cardvideo',
            name='video',
            field=models.FileField(upload_to='cards/videos/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='discountrequest',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Комментарий администратора при отклонении/одобрении', null=True, verbose_name='Комментарий администратора'),
        ),
        migrations.AlterField(
            model_name='discountrequest',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_requests', to='cards.card', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='discountrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='discountrequest',
            name='discount_percent',
            field=models.FloatField(blank=True, editable=False, help_text='Процент скидки (вычисляется автоматически)', null=True, verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='discountrequest',
            name='message',
            field=models.TextField(blank=True, help_text='Причина или комментарий к запросу', null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='discountrequest',
            name='original_price',
            field=models.DecimalField(decimal_places=2, help_text='Текущая цена карточки', max_digits=12, verbose_name='Исходная цена'),
        ),
        migrations.AlterField(
            model_name='discountrequest',
            name='requested_price',
            field=models.DecimalField(decimal_places=2, help_text='Желаемая цена от пользователя', max_digits=12, verbose_name='Запрошенная цена'),
        ),
        migrations.AlterField(
            model_name='discountrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='discountrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='discountrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='cards.card', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлена'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='review',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to='cards.card', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1★'), (2, '2★'), (3, '3★'), (4, '4★'), (5, '5★')], help_text='Оценка от 1 до 5', verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='query',
            field=models.CharField(max_length=255, verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
