# Generated by Django 5.2.7 on 2025-12-28 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0024_alter_callrequest_options_alter_card_options_and_more'),
        ('developers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='carddocument',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='cardimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cardquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cardreview',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='cardvideo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='discountrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={},
        ),
        migrations.AddField(
            model_name='cardreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aiassistant',
            name='system_prompt',
            field=models.TextField(default='Ты профессиональный консультант по недвижимости. Помогай пользователям найти идеальный дом.\nТы имеешь доступ к базе данных карточек недвижимости и можешь давать персонализированные рекомендации.\n\nИНСТРУКЦИИ ПО ПОВЕДЕНИЮ:\n- Если вопрос про недвижимость (квартиры, дома, аренду, ипотеку, цены, районы и т.д.) - предоставляй доступные варианты из базы и рекомендации\n- Если вопрос НЕ про недвижимость:\n  * Ответь на вопрос человека дружелюбно и по существу (не отказывай, не отправляй в стол)\n  * ПОТОМ предложи помощь с недвижимостью если уместно\n  * Например: "Месси - великий футболист. Если захочешь выбрать квартиру в хорошем районе, я помогу!"\n- Будь гибким и естественным в общении\n- Если пользователь спрашивает про условия покупки, ипотеку, эскроу, документы, налоги - это про недвижимость, помогай активно\n\nВАЖНО - Форматирование ответов:\n- Пиши чистым текстом без markdown разметки\n- НЕ используй ** для жирного текста\n- НЕ используй символы \\n для переносов (пиши обычные абзацы)\n- НЕ используй # для заголовков\n- Используй простые тире - для списков\n- Отвечай кратко и по делу\n\nОтвечай на русском языке, будь вежлив и информативен.', help_text='Системный промпт для AI'),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to='cards.card'),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='card',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='building_material',
            field=models.CharField(choices=[('brick', 'Кирпичный'), ('panel', 'Панельный'), ('monolith', 'Монолитный')], default='brick', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.CharField(choices=[('flat', 'Квартира'), ('new_building', 'Новостройка')], default='flat', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='ceiling_height',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='city',
            field=models.IntegerField(choices=[(1, 'Махачкала'), (2, 'Каспийск'), (3, 'Дербент')], default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='developers.developer'),
        ),
        migrations.AlterField(
            model_name='card',
            name='elevator',
            field=models.CharField(choices=[('none', 'Нет'), ('passenger', 'Пассажирский'), ('cargo', 'Грузовой')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='floors_total',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='house_type',
            field=models.CharField(choices=[('private', 'Частный дом'), ('apartment', 'Квартира')], default='apartment', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='list_curations',
            field=models.TextField(blank=True, default='[]', help_text='JSON массив ID карточек для подборок (рекомендации, похожие объекты)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='parking',
            field=models.CharField(choices=[('none', 'Нет'), ('underground', 'Подземная')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='carddocument',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cards.card'),
        ),
        migrations.AlterField(
            model_name='carddocument',
            name='document_list',
            field=models.ForeignKey(blank=True, help_text='Подборка, к которой относится документ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cards.carddocumentlist'),
        ),
        migrations.AlterField(
            model_name='carddocument',
            name='file',
            field=models.FileField(upload_to='cards/documents/'),
        ),
        migrations.AlterField(
            model_name='carddocument',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='carddocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cards.card'),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='image',
            field=models.ImageField(upload_to='cards/img/'),
        ),
        migrations.AlterField(
            model_name='cardquestion',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardquestion',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cards.card'),
        ),
        migrations.AlterField(
            model_name='cardquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cardquestion',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cardquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cardreview',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cards.card'),
        ),
        migrations.AlterField(
            model_name='cardreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cardreview',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='cardreview',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cardreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cardvideo',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='cards.card'),
        ),
        migrations.AlterField(
            model_name='cardvideo',
            name='video',
            field=models.FileField(upload_to='cards/videos/'),
        ),
        migrations.AlterField(
            model_name='discountrequest',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Комментарий администратора при отклонении/одобрении', null=True),
        ),
        migrations.AlterField(
            model_name='discountrequest',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_requests', to='cards.card'),
        ),
        migrations.AlterField(
            model_name='discountrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discountrequest',
            name='discount_percent',
            field=models.FloatField(blank=True, editable=False, help_text='Процент скидки (вычисляется автоматически)', null=True),
        ),
        migrations.AlterField(
            model_name='discountrequest',
            name='message',
            field=models.TextField(blank=True, help_text='Причина или комментарий к запросу', null=True),
        ),
        migrations.AlterField(
            model_name='discountrequest',
            name='original_price',
            field=models.DecimalField(decimal_places=2, help_text='Текущая цена карточки', max_digits=12),
        ),
        migrations.AlterField(
            model_name='discountrequest',
            name='requested_price',
            field=models.DecimalField(decimal_places=2, help_text='Желаемая цена от пользователя', max_digits=12),
        ),
        migrations.AlterField(
            model_name='discountrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='discountrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='discountrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='cards.card'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='query',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='cards.cardreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('review', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
