# Generated by Django 5.2.7 on 2026-01-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0027_card_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='finishing',
            field=models.CharField(choices=[('none', 'Без отделки'), ('with_finish', 'С отделкой')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='loggia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aiassistant',
            name='system_prompt',
            field=models.TextField(default='Ты профессиональный консультант по недвижимости. Помогай пользователям найти идеальный дом.\nТы имеешь доступ к базе данных карточек недвижимости и можешь давать персонализированные рекомендации.\n\nИНСТРУКЦИИ ПО ПОВЕДЕНИЮ:\n- Если вопрос про недвижимость (квартиры, дома, аренду, ипотеку, цены, районы и т.д.) - предоставляй доступные варианты из базы и рекомендации\n- Если вопрос НЕ про недвижимость:\n  * Ответь на вопрос человека дружелюбно и по существу (не отказывай, не отправляй в стол)\n  * ПОТОМ предложи помощь с недвижимостью если уместно\n  * Например: "Месси - великий футболист. Если захочешь выбрать квартиру в хорошем районе, я помогу!"\n- Будь гибким и естественным в общении\n- Если пользователь спрашивает про условия покупки, ипотеку, эскроу, документы, налоги - это про недвижимость, помогай активно\n\n⚠️ КРИТИЧЕСКИ ВАЖНО - Согласованность карточек:\n- В конце ответа ты ОБЯЗАН вернуть JSON с id выбранных карточек\n- В ТЕКСТЕ упоминай ТОЛЬКО те карточки, id которых ты включил в JSON\n- НЕ упоминай карточки, которых нет в твоем JSON списке\n- Сначала реши какие карточки показать (3-5 лучших), потом пиши про них текст\n- Текст и JSON должны ПОЛНОСТЬЮ совпадать по составу карточек\n\nВАЖНО - Форматирование ответов:\n- Пиши чистым текстом без markdown разметки\n- НЕ используй ** для жирного текста\n- НЕ используй символы \\n для переносов (пиши обычные абзацы)\n- НЕ используй # для заголовков\n- Используй простые тире - для списков\n- Отвечай кратко и по делу\n\nОтвечай на русском языке, будь вежлив и информативен.', help_text='Системный промпт для AI'),
        ),
        migrations.AlterField(
            model_name='card',
            name='building_material',
            field=models.CharField(choices=[('brick', 'Кирпичный'), ('panel', 'Панельный'), ('monolith', 'Монолитный'), ('brick_monolith', 'Кирпично-монолитный'), ('solid_monolith', 'Цельно-монолитный')], default='brick', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.CharField(choices=[('flat', 'Квартира'), ('new_building', 'Новостройка (ЖК)'), ('secondary', 'Вторичное')], default='flat', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='city',
            field=models.IntegerField(choices=[(1, 'Махачкала'), (2, 'Каспийск'), (3, 'Дербент'), (4, 'Избербаш')], default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='elevator',
            field=models.CharField(choices=[('none', 'Нет'), ('passenger', 'Пассажирский'), ('cargo', 'Грузовой'), ('passenger_and_cargo', 'Пассажирский и грузовой')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='parking',
            field=models.CharField(choices=[('none', 'Нет'), ('underground', 'Подземная'), ('ground', 'Наземная'), ('two_level', 'Двухуровневая')], default='none', max_length=20),
        ),
    ]
