# Generated by Django 5.2.7 on 2026-01-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0028_card_finishing_card_loggia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.CharField(choices=[('flat', 'Квартира'), ('new_building', 'Новостройка'), ('secondary', 'Вторичное')], default='flat', max_length=50),
        ),
    ]
