# Generated by Django 5.2.8 on 2026-02-05 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0030_promotion_promotionitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='building_material',
        ),
        migrations.AddField(
            model_name='card',
            name='complex_type',
            field=models.CharField(choices=[('residential', 'Жилой комплекс'), ('apart', 'Апарт-комплекс')], default='residential', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='phone',
            field=models.CharField(default='92-62-66', max_length=20, verbose_name='Телефон застройщика'),
        ),
        migrations.AlterField(
            model_name='card',
            name='ceiling_height',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='elevator',
            field=models.CharField(choices=[('none', 'Нет'), ('passenger', 'Пассажирский'), ('cargo', 'Грузовой'), ('cargo_passenger', 'Грузопассажирский'), ('passenger_and_cargo', 'Пассажирский и грузовой')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='house_type',
            field=models.CharField(choices=[('brick', 'Кирпичный'), ('panel', 'Панельный'), ('monolith', 'Монолитный'), ('brick_monolith', 'Кирпично-монолитный'), ('solid_monolith', 'Цельно-монолитный')], default='brick', max_length=50),
        ),
        migrations.CreateModel(
            name='CardFloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cards/floor_plans/')),
                ('title', models.CharField(blank=True, help_text='Название планировки (опционально)', max_length=100)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='cards.card')),
            ],
        ),
    ]
