# Generated by Django 5.2.7 on 2026-07-12 20:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0032_card_3d_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepLinkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ios_team_id', models.CharField(default='48RARN99NS', help_text='Team ID из Apple Developer Account', max_length=20, verbose_name='Apple Team ID')),
                ('ios_bundle_id', models.CharField(default='com.dreamhouse.app', max_length=100, verbose_name='iOS Bundle ID')),
                ('appstore_url', models.URLField(default='https://apps.apple.com/app/dreamhouse/id000000000', help_text='Ссылка на приложение в App Store', max_length=500, verbose_name='App Store URL')),
                ('android_package_name', models.CharField(default='com.dreamhouse.app', max_length=100, verbose_name='Android Package Name')),
                ('android_sha256_fingerprint', models.CharField(default='SHA256_ОТПЕЧАТОК_ВАШЕГО_КЛЮЧА', help_text='SHA-256 отпечаток signing key из Google Play Console', max_length=200, verbose_name='SHA-256 Fingerprint')),
                ('playstore_url', models.URLField(default='https://play.google.com/store/apps/details?id=com.dreamhouse.app', help_text='Ссылка на приложение в Google Play', max_length=500, verbose_name='Google Play URL')),
                ('deep_link_paths', models.CharField(default='/ref/*', help_text='Через запятую, например: /ref/*, /invite/*', max_length=500, verbose_name='Пути для deep links')),
            ],
            options={
                'verbose_name': 'Настройка Deep Links',
                'verbose_name_plural': 'Настройки Deep Links',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Политика конфиденциальности', max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, help_text='Полный текст политики конфиденциальности (поддерживает HTML)', null=True, verbose_name='Содержание')),
                ('document', models.FileField(blank=True, help_text='Загрузите PDF или Word файл с политикой конфиденциальности', null=True, upload_to='documents/privacy/', verbose_name='Документ (PDF/Word)')),
                ('version', models.CharField(default='1.0', max_length=50, verbose_name='Версия')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Дата вступления в силу')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, help_text='Только одна политика может быть активной', verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Политика конфиденциальности',
                'verbose_name_plural': 'Политики конфиденциальности',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InProgressCallRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Заявка в работе',
                'verbose_name_plural': 'В работе',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cards.callrequest',),
        ),
        migrations.CreateModel(
            name='NewCallRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Новая заявка',
                'verbose_name_plural': 'Новые заявки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cards.callrequest',),
        ),
        migrations.CreateModel(
            name='ProcessedCallRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Обработанная заявка',
                'verbose_name_plural': 'Обработанные',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cards.callrequest',),
        ),
        migrations.AlterModelOptions(
            name='callrequest',
            options={'verbose_name': 'Заявка на звонок', 'verbose_name_plural': 'Заявки на звонок'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='callrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('processed', 'Обработан')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='card',
            name='accepts_car_barter',
            field=models.BooleanField(default=False, verbose_name='Бартер авто'),
        ),
        migrations.AddField(
            model_name='card',
            name='accepts_land_barter',
            field=models.BooleanField(default=False, verbose_name='Бартер земли'),
        ),
        migrations.AddField(
            model_name='card',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Скрыт'),
        ),
        migrations.AddField(
            model_name='card',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Закреплён'),
        ),
        migrations.AddField(
            model_name='card',
            name='prices_on_request',
            field=models.BooleanField(default=False, help_text='Цены и условия по запросу у менеджера', verbose_name='Цены по запросу'),
        ),
        migrations.AlterField(
            model_name='aiassistant',
            name='api_provider',
            field=models.CharField(choices=[('openai', 'OpenAI (GPT-4)'), ('openrouter', 'OpenRouter (обход блокировки)'), ('anthropic', 'Anthropic (Claude)'), ('deepseek', 'DeepSeek (R1)'), ('disabled', 'Отключен')], default='openai', max_length=50),
        ),
        migrations.AlterField(
            model_name='aiassistant',
            name='model_name',
            field=models.CharField(choices=[('gpt-4.1', 'GPT-4.1 (новейшая)'), ('gpt-4.1-mini', 'GPT-4.1 Mini (быстрая и дешёвая)'), ('gpt-4.1-nano', 'GPT-4.1 Nano (самая быстрая)'), ('gpt-4o', 'GPT-4o (мультимодальная)'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-4', 'GPT-4'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('o1', 'o1 (reasoning)'), ('o1-mini', 'o1 Mini'), ('o1-preview', 'o1 Preview'), ('o3-mini', 'o3 Mini'), ('claude-3-opus-20240229', 'Claude 3 Opus'), ('claude-3-sonnet-20240229', 'Claude 3 Sonnet'), ('claude-3-haiku-20240307', 'Claude 3 Haiku'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet'), ('deepseek-chat', 'DeepSeek Chat'), ('deepseek-reasoner', 'DeepSeek Reasoner (R1)')], default='gpt-4', help_text='Выберите модель ИИ', max_length=100),
        ),
        migrations.CreateModel(
            name='CardPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('discount', 'Скидка'), ('charity', 'Благотворительность'), ('barter', 'Бартер'), ('gift', 'Подарок'), ('other', 'Другое')], max_length=20, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_promotions', to='cards.card')),
            ],
            options={
                'verbose_name': 'Спец-условие / акция ЖК',
                'verbose_name_plural': 'Спец-условия / акции ЖК',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_type', models.CharField(blank=True, choices=[('studio', 'Студия'), ('1k', '1-комнатная'), ('2k', '2-комнатная'), ('3k', '3-комнатная'), ('2e', '2-евро'), ('3e', '3-евро')], help_text='Если тариф только для конкретного типа квартиры', max_length=20)),
                ('floor_from', models.PositiveIntegerField(blank=True, help_text='Нижний этаж диапазона, для которого действует тариф (пусто = все этажи)', null=True, verbose_name='Этаж от')),
                ('floor_to', models.PositiveIntegerField(blank=True, help_text='Верхний этаж диапазона (пусто = без ограничения)', null=True, verbose_name='Этаж до')),
                ('is_cash', models.BooleanField(default=False, help_text='True = наличная цена (term_months игнорируется)')),
                ('term_months', models.PositiveIntegerField(default=0, help_text='Срок рассрочки в месяцах. 0 для is_cash=True')),
                ('down_payment_type', models.CharField(blank=True, choices=[('percent', 'Процент от стоимости'), ('fixed', 'Фиксированная сумма')], help_text='Процент или фиксированная сумма', max_length=10, verbose_name='Тип взноса')),
                ('down_payment_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Процент от стоимости квартиры', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Взнос, %')),
                ('down_payment_min_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Нижняя граница диапазона взноса', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Взнос от, ₽')),
                ('down_payment_max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Верхняя граница диапазона взноса (пусто = без ограничений)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Взнос до, ₽')),
                ('price_per_sqm', models.DecimalField(decimal_places=2, help_text='Цена за м² при этом тарифе', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за м²')),
                ('accepts_mat_capital', models.BooleanField(default=False, verbose_name='Мат. капитал')),
                ('mat_capital_note', models.CharField(blank=True, help_text='Условия принятия мат. капитала', max_length=255)),
                ('extra_conditions', models.JSONField(blank=True, default=dict, help_text='Нестандартные условия, не покрытые полями')),
                ('note', models.TextField(blank=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='cards.card')),
            ],
            options={
                'verbose_name': 'Тариф рассрочки',
                'verbose_name_plural': 'Тарифы рассрочки',
                'ordering': ['card', 'floor_from', 'is_cash', 'term_months'],
                'indexes': [models.Index(fields=['card', 'is_active'], name='cards_insta_card_id_c81283_idx')],
            },
        ),
    ]
