# Generated by Django 5.2.7 on 2026-07-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0041_merge_20260712_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Одно слово без пробелов, например Стандарт55', max_length=100, unique=True, verbose_name='Название')),
                ('text', models.TextField(help_text='Одна строка — один тариф: «взнос +надбавка_к_цене срок» или «нал +надбавка». Например: 300к +15000 55', verbose_name='Условия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон рассрочки',
                'verbose_name_plural': 'Шаблоны рассрочки',
                'ordering': ['name'],
            },
        ),
    ]
