# Generated by Django 5.2.8 on 2026-02-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
