# Generated by Django 5.2.8 on 2026-02-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='created_by',
        ),
        migrations.AddField(
            model_name='developer',
            name='phone',
            field=models.CharField(default='92-62-66', max_length=20, verbose_name='Телефон'),
        ),
    ]
